apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: ClusterIP 
  selector:
    matchLabels:
      app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin