apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ams-ingress
spec:
  rules:
  - host: pma.ams-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pma-service
            port:
              number: 80

