apiVersion: v1
kind: Service
metadata:
  name: mysql-article-svc
  namespace: ams-database
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
