apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      # Communicate Between Containers in the Same Pod Using a Shared Volume
      containers:
      - name: bdservicearticle 
        image: mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.5"
          requests:
            memory: "300Mi"
            cpu: "0.3"
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: root-password   
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password  
        - name: MYSQL_DATABASE 
          valueFrom:
            configMapKeyRef:
              name: db-cm
              key: article-db-name


      - name: bdserviceprovider 
        image: mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.5"
          requests:
            memory: "300Mi"
            cpu: "0.3"
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: root-password   
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password 
        - name: MYSQL_DATABASE 
          valueFrom:
            configMapKeyRef:
              name: db-cm
              key: provider-db-name

        volumeMounts:
        - name: mysql-shared-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-shared-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-dynamic
