apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  namespace: ams-database
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-provider-db
          image: mysql
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-cm
                  key: provider-db-name
          volumeMounts:
            - name: mysql-persistent-shared-storage
              mountPath: /var/lib/mysql

        - name: mysql-article-db
          image: mysql
          ports:
            - containerPort: 3001
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-cm
                  key: article-db-name
          volumeMounts:
            - name: mysql-persistent-shared-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage # this volume will be used for database storage.
          persistentVolumeClaim:
            claimName: mysql-pvc-dynamic
